let currentProject={name:"Novo projeto",html:"",css:"",javascript:""};
const $=id=>document.getElementById(id), preview=$("preview"), code=$("code"), messages=$("messages");
const formatCredits=v=>Number(v||0).toLocaleString("pt-BR");
async function refreshMe(){try{const r=await fetch("/api/me",{credentials:"same-origin"});const d=await r.json();if(r.ok){$("tokens").textContent=`${formatCredits(d.remaining)} créditos`;$(`loginBtn`).textContent=d.email;return true} }catch{} $("tokens").textContent="Faça login";$("loginBtn").textContent="Entrar";return false}
function render(){preview.srcdoc=`<!doctype html><html><head><style>${currentProject.css}</style></head><body>${currentProject.html}<script>${currentProject.javascript}\<\/script></body></html>`;code.textContent=`index.html\n\n${currentProject.html}\n\nstyle.css\n\n${currentProject.css}\n\napp.js\n\n${currentProject.javascript}`}
function addMessage(text,type){const e=document.createElement("div");e.className=`msg ${type}`;e.textContent=text;messages.appendChild(e);messages.scrollTop=messages.scrollHeight}
async function loginFlow(){const email=window.prompt("Digite seu e-mail:");if(!email)return;const password=window.prompt("Digite sua senha (mínimo 6 caracteres):");if(!password)return;let r=await fetch("/api/auth/login",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});let d=await r.json();if(r.status===401){if(window.confirm("Conta não encontrada ou senha incorreta. Quer criar uma conta com estes dados?")){r=await fetch("/api/auth/register",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});d=await r.json()}}if(!r.ok)return window.alert(d.error||"Não foi possível entrar.");await refreshMe();addMessage("Conta conectada com sucesso! Seus créditos ficam salvos na conta.","ai")}
$("loginBtn").onclick=loginFlow;
$("promptForm").onsubmit=async e=>{e.preventDefault();const promptText=$("prompt").value.trim();if(!promptText)return;if(!(await refreshMe())){await loginFlow();if(!(await refreshMe()))return;}const button=e.submitter||e.querySelector("button");if(button)button.disabled=true;addMessage(promptText,"user");$("prompt").value="";addMessage("Gerando seu site...","ai");try{const r=await fetch("/api/generate",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:promptText,files:currentProject})});const d=await r.json();if(!r.ok)throw Error(d.error||"Erro");currentProject={...currentProject,...d.files};$("tokens").textContent=`${formatCredits(d.remaining)} créditos`;render();addMessage(`Site atualizado! ${formatCredits(d.tokens)} créditos usados.`,`ai`)}catch(err){addMessage("Erro: "+err.message,"ai");await refreshMe()}finally{if(button)button.disabled=false}};
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=b.dataset.tab==="preview";preview.hidden=!p;code.hidden=p});
$("newProject").onclick=()=>{currentProject={name:"Novo projeto",html:"",css:"",javascript:""};$("projectName").textContent=currentProject.name;render()};
$("exportBtn").onclick=()=>{const blob=new Blob([`<!doctype html><html><head><style>${currentProject.css}</style></head><body>${currentProject.html}<script>${currentProject.javascript}\<\/script></body></html>`],{type:"text/html"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="forgeai-site.html";a.click()};
$("publishBtn").onclick=()=>alert("Para publicar, use uma hospedagem com backend. Nunca coloque a chave da OpenAI no navegador.");
refreshMe();render();
