let currentProject={name:"Novo projeto",html:"",css:"",javascript:""};
const $=id=>document.getElementById(id), preview=$("preview"), code=$("code"), messages=$("messages");
function render(){preview.srcdoc=`<!doctype html><html><head><style>${currentProject.css}</style></head><body>${currentProject.html}<script>${currentProject.javascript}<\/script></body></html>`;code.textContent=`index.html\n\n${currentProject.html}\n\nstyle.css\n\n${currentProject.css}\n\nscript.js\n\n${currentProject.javascript}`}
function addMessage(text,type){const e=document.createElement("div");e.className=`msg ${type}`;e.textContent=text;messages.appendChild(e);messages.scrollTop=messages.scrollHeight}
$("promptForm").onsubmit=async e=>{e.preventDefault();const prompt=$("prompt").value.trim();if(!prompt)return;addMessage(prompt,"user");$("prompt").value="";addMessage("Gerando seu site...","ai");try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,files:currentProject})});const d=await r.json();if(!r.ok)throw Error(d.error||"Erro");currentProject={...currentProject,...d.files};$("tokens").textContent=Number(d.tokens).toLocaleString("pt-BR")+" tokens";render();addMessage("Site atualizado!","ai")}catch(err){addMessage("Erro: "+err.message,"ai")}}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");const p=b.dataset.tab==="preview";preview.hidden=!p;code.hidden=p});
$("newProject").onclick=()=>{currentProject={name:"Novo projeto",html:"",css:"",javascript:""};$("projectName").textContent=currentProject.name;render()};
$("exportBtn").onclick=()=>{const blob=new Blob([`<!doctype html><html><head><style>${currentProject.css}</style></head><body>${currentProject.html}<script>${currentProject.javascript}<\/script></body></html>`],{type:"text/html"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="forgeai-site.html";a.click()};
$("publishBtn").onclick=()=>alert("Para publicar, use uma hospedagem com backend. Nunca coloque a chave da OpenAI no navegador.");
render();
